//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoVista.Core.Tests.UIMetaData {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetaDataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal MetaDataResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LagoVista.Core.Tests.UIMetaData.MetaDataResources", typeof(MetaDataResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enum 1 Help.
        /// </summary>
        public static string Enum1_Help {
            get {
                return ResourceManager.GetString("Enum1_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enum 1.
        /// </summary>
        public static string Enum1_Label {
            get {
                return ResourceManager.GetString("Enum1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enum 2 Help.
        /// </summary>
        public static string Enum2_Help {
            get {
                return ResourceManager.GetString("Enum2_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enum 2.
        /// </summary>
        public static string Enum2_Label {
            get {
                return ResourceManager.GetString("Enum2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enum 3 Help.
        /// </summary>
        public static string Enum3_Help {
            get {
                return ResourceManager.GetString("Enum3_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enum 3 Label.
        /// </summary>
        public static string Enum3_Label {
            get {
                return ResourceManager.GetString("Enum3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This is field 1 help.
        /// </summary>
        public static string Field1_Help {
            get {
                return ResourceManager.GetString("Field1_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field 1.
        /// </summary>
        public static string Field1_Label {
            get {
                return ResourceManager.GetString("Field1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field1 is required.
        /// </summary>
        public static string Field1_RequiredMessage1 {
            get {
                return ResourceManager.GetString("Field1_RequiredMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Summary -Field 1.
        /// </summary>
        public static string Field1_Summary {
            get {
                return ResourceManager.GetString("Field1_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field One WaterMark.
        /// </summary>
        public static string Field1_WaterMark {
            get {
                return ResourceManager.GetString("Field1_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This is field 2 help.
        /// </summary>
        public static string Field2_Help {
            get {
                return ResourceManager.GetString("Field2_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field 2.
        /// </summary>
        public static string Field2_Label {
            get {
                return ResourceManager.GetString("Field2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field 2 needs some regex love.
        /// </summary>
        public static string Field2_RegExMessage {
            get {
                return ResourceManager.GetString("Field2_RegExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Summary -Field 2.
        /// </summary>
        public static string Field2_Summary {
            get {
                return ResourceManager.GetString("Field2_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Column Header.
        /// </summary>
        public static string Field3_Column_Header {
            get {
                return ResourceManager.GetString("Field3_Column_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field 3.
        /// </summary>
        public static string Field3_Label {
            get {
                return ResourceManager.GetString("Field3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Summary - Field 3.
        /// </summary>
        public static string Field3_Summary {
            get {
                return ResourceManager.GetString("Field3_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Compare Resource.
        /// </summary>
        public static string Field4_CompareResource {
            get {
                return ResourceManager.GetString("Field4_CompareResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field 4.
        /// </summary>
        public static string Field4_Label {
            get {
                return ResourceManager.GetString("Field4_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field 5.
        /// </summary>
        public static string Field5_Label {
            get {
                return ResourceManager.GetString("Field5_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Model 3 Description.
        /// </summary>
        public static string Model1_Description {
            get {
                return ResourceManager.GetString("Model1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Model 1 Help.
        /// </summary>
        public static string Model1_Help {
            get {
                return ResourceManager.GetString("Model1_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Model One.
        /// </summary>
        public static string Model1_Title {
            get {
                return ResourceManager.GetString("Model1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Model 2 Description.
        /// </summary>
        public static string Model2_Description {
            get {
                return ResourceManager.GetString("Model2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Model 2 Help.
        /// </summary>
        public static string Model2_Help {
            get {
                return ResourceManager.GetString("Model2_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Model Two.
        /// </summary>
        public static string Model2_Title {
            get {
                return ResourceManager.GetString("Model2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Model Three Description.
        /// </summary>
        public static string Model3_Description {
            get {
                return ResourceManager.GetString("Model3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Model Three Help.
        /// </summary>
        public static string Model3_Help {
            get {
                return ResourceManager.GetString("Model3_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Model Three.
        /// </summary>
        public static string Model3_Title {
            get {
                return ResourceManager.GetString("Model3_Title", resourceCulture);
            }
        }
    }
}
