// <auto-generated />
// Generated deterministically by Software Logistics Build Server from .resx source.
using System.Globalization;
using System.Reflection;

namespace LagoVista.Core.Networking.Resources
{
    public class NetworkingResources
    {
        private static global::System.Resources.ResourceManager _resourceManager;

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(_resourceManager, null))
                    _resourceManager = new global::System.Resources.ResourceManager("LagoVista.Core.Networking.Resources.NetworkingResources", typeof(NetworkingResources).GetTypeInfo().Assembly);
                return _resourceManager;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private static string GetResourceString(string key, params string[] tokens)
        {
            var str = ResourceManager.GetString(key, CultureInfo.CurrentCulture);
            for (var i = 0; i < tokens.Length; i += 2)
                str = str.Replace(tokens[i], tokens[i + 1]);
            return str;
        }

//Resources:NetworkingResources:MQTT_QOS0
        public static string MQTT_QOS0 { get { return GetResourceString("MQTT_QOS0"); } }
//Resources:NetworkingResources:MQTT_QOS1
        public static string MQTT_QOS1 { get { return GetResourceString("MQTT_QOS1"); } }
//Resources:NetworkingResources:MQTT_QOS2
        public static string MQTT_QOS2 { get { return GetResourceString("MQTT_QOS2"); } }
//Resources:NetworkingResources:Subscription_Description
        public static string Subscription_Description { get { return GetResourceString("Subscription_Description"); } }
//Resources:NetworkingResources:Subscription_QOS
        public static string Subscription_QOS { get { return GetResourceString("Subscription_QOS"); } }
//Resources:NetworkingResources:Subscription_QOS_Help
        public static string Subscription_QOS_Help { get { return GetResourceString("Subscription_QOS_Help"); } }
//Resources:NetworkingResources:Subscription_QOS_Select
        public static string Subscription_QOS_Select { get { return GetResourceString("Subscription_QOS_Select"); } }
//Resources:NetworkingResources:Subscription_Title
        public static string Subscription_Title { get { return GetResourceString("Subscription_Title"); } }
//Resources:NetworkingResources:Subscription_Topic
        public static string Subscription_Topic { get { return GetResourceString("Subscription_Topic"); } }
//Resources:NetworkingResources:Subscription_Topic_Help
        public static string Subscription_Topic_Help { get { return GetResourceString("Subscription_Topic_Help"); } }

        public static class Names
        {
            public const string MQTT_QOS0 = "MQTT_QOS0";
            public const string MQTT_QOS1 = "MQTT_QOS1";
            public const string MQTT_QOS2 = "MQTT_QOS2";
            public const string Subscription_Description = "Subscription_Description";
            public const string Subscription_QOS = "Subscription_QOS";
            public const string Subscription_QOS_Help = "Subscription_QOS_Help";
            public const string Subscription_QOS_Select = "Subscription_QOS_Select";
            public const string Subscription_Title = "Subscription_Title";
            public const string Subscription_Topic = "Subscription_Topic";
            public const string Subscription_Topic_Help = "Subscription_Topic_Help";
        }
    }
}

