//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoVista.DocBuilder.Tests.TestResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal TestResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LagoVista.DocBuilder.Tests.TestResources.TestResources", typeof(TestResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field 1.
        /// </summary>
        public static string Field1_Caption {
            get {
                return ResourceManager.GetString("Field1_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This is help on Field 1.
        /// </summary>
        public static string Field1_Help {
            get {
                return ResourceManager.GetString("Field1_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field 2.
        /// </summary>
        public static string Field2_Caption {
            get {
                return ResourceManager.GetString("Field2_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This is help on Field 2.
        /// </summary>
        public static string Field2_Help {
            get {
                return ResourceManager.GetString("Field2_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Field 3.
        /// </summary>
        public static string Field3_Caption {
            get {
                return ResourceManager.GetString("Field3_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Model1.
        /// </summary>
        public static string Model1_Name {
            get {
                return ResourceManager.GetString("Model1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Model2.
        /// </summary>
        public static string Model2_Name {
            get {
                return ResourceManager.GetString("Model2_Name", resourceCulture);
            }
        }
    }
}
