// <auto-generated />
// Generated deterministically by Software Logistics Build Server from .resx source.
using System.Globalization;
using System.Reflection;

namespace LagoVista.Core.Tests.Resources.Models
{
    public class ValidationResources
    {
        private static global::System.Resources.ResourceManager _resourceManager;

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(_resourceManager, null))
                    _resourceManager = new global::System.Resources.ResourceManager("LagoVista.Core.Tests.Models.ValidationResources", typeof(ValidationResources).GetTypeInfo().Assembly);
                return _resourceManager;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private static string GetResourceString(string key, params string[] tokens)
        {
            var str = ResourceManager.GetString(key, CultureInfo.CurrentCulture);
            for (var i = 0; i < tokens.Length; i += 2)
                str = str.Replace(tokens[i], tokens[i + 1]);
            return str;
        }

//Resources:ValidationResources:CustomValidationMessage
        public static string CustomValidationMessage { get { return GetResourceString("CustomValidationMessage"); } }
//Resources:ValidationResources:EnumFive
        public static string EnumFive { get { return GetResourceString("EnumFive"); } }
//Resources:ValidationResources:EnumFour
        public static string EnumFour { get { return GetResourceString("EnumFour"); } }
//Resources:ValidationResources:EnumOne
        public static string EnumOne { get { return GetResourceString("EnumOne"); } }
//Resources:ValidationResources:EnumThree
        public static string EnumThree { get { return GetResourceString("EnumThree"); } }
//Resources:ValidationResources:EnumTwo
        public static string EnumTwo { get { return GetResourceString("EnumTwo"); } }
//Resources:ValidationResources:FirstNameLabel
        public static string FirstNameLabel { get { return GetResourceString("FirstNameLabel"); } }
//Resources:ValidationResources:KeyIsBad
        public static string KeyIsBad { get { return GetResourceString("KeyIsBad"); } }
//Resources:ValidationResources:RegExMessage
        public static string RegExMessage { get { return GetResourceString("RegExMessage"); } }

        public static class Names
        {
            public const string CustomValidationMessage = "CustomValidationMessage";
            public const string EnumFive = "EnumFive";
            public const string EnumFour = "EnumFour";
            public const string EnumOne = "EnumOne";
            public const string EnumThree = "EnumThree";
            public const string EnumTwo = "EnumTwo";
            public const string FirstNameLabel = "FirstNameLabel";
            public const string KeyIsBad = "KeyIsBad";
            public const string RegExMessage = "RegExMessage";
        }
    }
}

namespace LagoVista.Core.Tests.Resources.UIMetaData
{
    public class MetaDataResources
    {
        private static global::System.Resources.ResourceManager _resourceManager;

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(_resourceManager, null))
                    _resourceManager = new global::System.Resources.ResourceManager("LagoVista.Core.Tests.UIMetaData.MetaDataResources", typeof(MetaDataResources).GetTypeInfo().Assembly);
                return _resourceManager;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private static string GetResourceString(string key, params string[] tokens)
        {
            var str = ResourceManager.GetString(key, CultureInfo.CurrentCulture);
            for (var i = 0; i < tokens.Length; i += 2)
                str = str.Replace(tokens[i], tokens[i + 1]);
            return str;
        }

//Resources:MetaDataResources:BaseField1
        public static string BaseField1 { get { return GetResourceString("BaseField1"); } }
//Resources:MetaDataResources:BaseField1_Help
        public static string BaseField1_Help { get { return GetResourceString("BaseField1_Help"); } }
//Resources:MetaDataResources:BaseField1_Requied
        public static string BaseField1_Requied { get { return GetResourceString("BaseField1_Requied"); } }
//Resources:MetaDataResources:BaseField1_WM
        public static string BaseField1_WM { get { return GetResourceString("BaseField1_WM"); } }
//Resources:MetaDataResources:Child1
        public static string Child1 { get { return GetResourceString("Child1"); } }
//Resources:MetaDataResources:Child2
        public static string Child2 { get { return GetResourceString("Child2"); } }
//Resources:MetaDataResources:Child3
        public static string Child3 { get { return GetResourceString("Child3"); } }
//Resources:MetaDataResources:ChildList1
        public static string ChildList1 { get { return GetResourceString("ChildList1"); } }
//Resources:MetaDataResources:ChildList2
        public static string ChildList2 { get { return GetResourceString("ChildList2"); } }
//Resources:MetaDataResources:Complex_Model
        public static string Complex_Model { get { return GetResourceString("Complex_Model"); } }
//Resources:MetaDataResources:Complex_Model_Help
        public static string Complex_Model_Help { get { return GetResourceString("Complex_Model_Help"); } }
//Resources:MetaDataResources:EntityHeader_Enum_Value1
        public static string EntityHeader_Enum_Value1 { get { return GetResourceString("EntityHeader_Enum_Value1"); } }
//Resources:MetaDataResources:EntityHeader_Enum_Value2
        public static string EntityHeader_Enum_Value2 { get { return GetResourceString("EntityHeader_Enum_Value2"); } }
//Resources:MetaDataResources:EntityHeader_Enum_Value3
        public static string EntityHeader_Enum_Value3 { get { return GetResourceString("EntityHeader_Enum_Value3"); } }
//Resources:MetaDataResources:Enum1_Help
        public static string Enum1_Help { get { return GetResourceString("Enum1_Help"); } }
//Resources:MetaDataResources:Enum1_Label
        public static string Enum1_Label { get { return GetResourceString("Enum1_Label"); } }
//Resources:MetaDataResources:Enum2_Help
        public static string Enum2_Help { get { return GetResourceString("Enum2_Help"); } }
//Resources:MetaDataResources:Enum2_Label
        public static string Enum2_Label { get { return GetResourceString("Enum2_Label"); } }
//Resources:MetaDataResources:Enum3_Help
        public static string Enum3_Help { get { return GetResourceString("Enum3_Help"); } }
//Resources:MetaDataResources:Enum3_Label
        public static string Enum3_Label { get { return GetResourceString("Enum3_Label"); } }
//Resources:MetaDataResources:Field1_Help
        public static string Field1_Help { get { return GetResourceString("Field1_Help"); } }
//Resources:MetaDataResources:Field1_Label
        public static string Field1_Label { get { return GetResourceString("Field1_Label"); } }
//Resources:MetaDataResources:Field1_RequiredMessage1
        public static string Field1_RequiredMessage1 { get { return GetResourceString("Field1_RequiredMessage1"); } }
//Resources:MetaDataResources:Field1_Summary
        public static string Field1_Summary { get { return GetResourceString("Field1_Summary"); } }
//Resources:MetaDataResources:Field1_WaterMark
        public static string Field1_WaterMark { get { return GetResourceString("Field1_WaterMark"); } }
//Resources:MetaDataResources:Field2_Help
        public static string Field2_Help { get { return GetResourceString("Field2_Help"); } }
//Resources:MetaDataResources:Field2_Label
        public static string Field2_Label { get { return GetResourceString("Field2_Label"); } }
//Resources:MetaDataResources:Field2_RegExMessage
        public static string Field2_RegExMessage { get { return GetResourceString("Field2_RegExMessage"); } }
//Resources:MetaDataResources:Field2_Summary
        public static string Field2_Summary { get { return GetResourceString("Field2_Summary"); } }
//Resources:MetaDataResources:Field3_Column_Header
        public static string Field3_Column_Header { get { return GetResourceString("Field3_Column_Header"); } }
//Resources:MetaDataResources:Field3_Label
        public static string Field3_Label { get { return GetResourceString("Field3_Label"); } }
//Resources:MetaDataResources:Field3_Summary
        public static string Field3_Summary { get { return GetResourceString("Field3_Summary"); } }
//Resources:MetaDataResources:Field4_CompareResource
        public static string Field4_CompareResource { get { return GetResourceString("Field4_CompareResource"); } }
//Resources:MetaDataResources:Field4_Label
        public static string Field4_Label { get { return GetResourceString("Field4_Label"); } }
//Resources:MetaDataResources:Field5_Label
        public static string Field5_Label { get { return GetResourceString("Field5_Label"); } }
//Resources:MetaDataResources:Model1_Description
        public static string Model1_Description { get { return GetResourceString("Model1_Description"); } }
//Resources:MetaDataResources:Model1_Help
        public static string Model1_Help { get { return GetResourceString("Model1_Help"); } }
//Resources:MetaDataResources:Model1_Title
        public static string Model1_Title { get { return GetResourceString("Model1_Title"); } }
//Resources:MetaDataResources:Model2_Description
        public static string Model2_Description { get { return GetResourceString("Model2_Description"); } }
//Resources:MetaDataResources:Model2_Help
        public static string Model2_Help { get { return GetResourceString("Model2_Help"); } }
//Resources:MetaDataResources:Model2_Title
        public static string Model2_Title { get { return GetResourceString("Model2_Title"); } }
//Resources:MetaDataResources:Model3_Description
        public static string Model3_Description { get { return GetResourceString("Model3_Description"); } }
//Resources:MetaDataResources:Model3_Help
        public static string Model3_Help { get { return GetResourceString("Model3_Help"); } }
//Resources:MetaDataResources:Model3_Title
        public static string Model3_Title { get { return GetResourceString("Model3_Title"); } }
//Resources:MetaDataResources:SubChild1
        public static string SubChild1 { get { return GetResourceString("SubChild1"); } }
//Resources:MetaDataResources:SubChild2
        public static string SubChild2 { get { return GetResourceString("SubChild2"); } }
//Resources:MetaDataResources:SubChildList1
        public static string SubChildList1 { get { return GetResourceString("SubChildList1"); } }
//Resources:MetaDataResources:SubChildList2
        public static string SubChildList2 { get { return GetResourceString("SubChildList2"); } }
//Resources:MetaDataResources:SubChildList3
        public static string SubChildList3 { get { return GetResourceString("SubChildList3"); } }

        public static class Names
        {
            public const string BaseField1 = "BaseField1";
            public const string BaseField1_Help = "BaseField1_Help";
            public const string BaseField1_Requied = "BaseField1_Requied";
            public const string BaseField1_WM = "BaseField1_WM";
            public const string Child1 = "Child1";
            public const string Child2 = "Child2";
            public const string Child3 = "Child3";
            public const string ChildList1 = "ChildList1";
            public const string ChildList2 = "ChildList2";
            public const string Complex_Model = "Complex_Model";
            public const string Complex_Model_Help = "Complex_Model_Help";
            public const string EntityHeader_Enum_Value1 = "EntityHeader_Enum_Value1";
            public const string EntityHeader_Enum_Value2 = "EntityHeader_Enum_Value2";
            public const string EntityHeader_Enum_Value3 = "EntityHeader_Enum_Value3";
            public const string Enum1_Help = "Enum1_Help";
            public const string Enum1_Label = "Enum1_Label";
            public const string Enum2_Help = "Enum2_Help";
            public const string Enum2_Label = "Enum2_Label";
            public const string Enum3_Help = "Enum3_Help";
            public const string Enum3_Label = "Enum3_Label";
            public const string Field1_Help = "Field1_Help";
            public const string Field1_Label = "Field1_Label";
            public const string Field1_RequiredMessage1 = "Field1_RequiredMessage1";
            public const string Field1_Summary = "Field1_Summary";
            public const string Field1_WaterMark = "Field1_WaterMark";
            public const string Field2_Help = "Field2_Help";
            public const string Field2_Label = "Field2_Label";
            public const string Field2_RegExMessage = "Field2_RegExMessage";
            public const string Field2_Summary = "Field2_Summary";
            public const string Field3_Column_Header = "Field3_Column_Header";
            public const string Field3_Label = "Field3_Label";
            public const string Field3_Summary = "Field3_Summary";
            public const string Field4_CompareResource = "Field4_CompareResource";
            public const string Field4_Label = "Field4_Label";
            public const string Field5_Label = "Field5_Label";
            public const string Model1_Description = "Model1_Description";
            public const string Model1_Help = "Model1_Help";
            public const string Model1_Title = "Model1_Title";
            public const string Model2_Description = "Model2_Description";
            public const string Model2_Help = "Model2_Help";
            public const string Model2_Title = "Model2_Title";
            public const string Model3_Description = "Model3_Description";
            public const string Model3_Help = "Model3_Help";
            public const string Model3_Title = "Model3_Title";
            public const string SubChild1 = "SubChild1";
            public const string SubChild2 = "SubChild2";
            public const string SubChildList1 = "SubChildList1";
            public const string SubChildList2 = "SubChildList2";
            public const string SubChildList3 = "SubChildList3";
        }
    }
}

